export declare function escapeStringForRegex(value: string): string;
export declare function unEscapeStringFromRegex(value: string): string;
export declare function stringStartsAsRegEx(str: string): boolean;
export declare function stringToJsRegex(str: string): RegExp;
export declare function stringToMs(str: string): number;
export declare function toNumberString(value: number | undefined | null): string;
export declare function toIntegerOrUndefined(value: string): number | undefined;
export declare function toFloatOrUndefined(value: string): number | undefined;
export declare function toPascalCase(string: string): string;
export declare function escapeRegex(value: string): string;
