export declare const standardTransformers: {
    noopTransformer: import("..").SynchronousDataTransformerInfo<import("./transformers/noop").NoopTransformerOptions>;
    filterFieldsTransformer: import("..").DataTransformerInfo<import("./transformers/filter").FilterOptions>;
    filterFieldsByNameTransformer: import("..").DataTransformerInfo<import("./transformers/filterByName").FilterFieldsByNameTransformerOptions>;
    filterFramesTransformer: import("..").DataTransformerInfo<import("./transformers/filter").FilterOptions>;
    filterFramesByRefIdTransformer: import("..").DataTransformerInfo<import("./transformers/filterByRefId").FilterFramesByRefIdTransformerOptions>;
    filterByValueTransformer: import("..").DataTransformerInfo<import("./transformers/filterByValue").FilterByValueTransformerOptions>;
    formatStringTransformer: import("..").DataTransformerInfo<import("./transformers/formatString").FormatStringTransformerOptions>;
    formatTimeTransformer: import("..").DataTransformerInfo<import("./transformers/formatTime").FormatTimeTransformerOptions>;
    orderFieldsTransformer: import("..").DataTransformerInfo<import("./transformers/order").OrderFieldsTransformerOptions>;
    organizeFieldsTransformer: import("..").DataTransformerInfo<import("./transformers/organize").OrganizeFieldsTransformerOptions>;
    reduceTransformer: import("..").DataTransformerInfo<import("./transformers/reduce").ReduceTransformerOptions>;
    concatenateTransformer: import("..").DataTransformerInfo<import("./transformers/concat").ConcatenateTransformerOptions>;
    calculateFieldTransformer: import("..").DataTransformerInfo<import("./transformers/calculateField").CalculateFieldTransformerOptions>;
    joinByFieldTransformer: import("..").SynchronousDataTransformerInfo<import("./transformers/joinByField").JoinByFieldOptions>;
    /** @deprecated */
    seriesToColumnsTransformer: import("..").SynchronousDataTransformerInfo<import("./transformers/joinByField").JoinByFieldOptions>;
    seriesToRowsTransformer: import("..").DataTransformerInfo<import("./transformers/seriesToRows").SeriesToRowsTransformerOptions>;
    renameFieldsTransformer: import("..").DataTransformerInfo<import("./transformers/rename").RenameFieldsTransformerOptions>;
    labelsToFieldsTransformer: import("..").SynchronousDataTransformerInfo<import("./transformers/labelsToFields").LabelsToFieldsOptions>;
    ensureColumnsTransformer: import("..").SynchronousDataTransformerInfo<any>;
    groupByTransformer: import("..").DataTransformerInfo<import("./transformers/groupBy").GroupByTransformerOptions>;
    sortByTransformer: import("..").DataTransformerInfo<import("./transformers/sortBy").SortByTransformerOptions>;
    mergeTransformer: import("..").DataTransformerInfo<import("./transformers/merge").MergeTransformerOptions>;
    renameByRegexTransformer: import("..").DataTransformerInfo<import("./transformers/renameByRegex").RenameByRegexTransformerOptions>;
    histogramTransformer: import("..").SynchronousDataTransformerInfo<import("./transformers/histogram").HistogramTransformerInputs>;
    convertFieldTypeTransformer: import("..").SynchronousDataTransformerInfo<import("./transformers/convertFieldType").ConvertFieldTypeTransformerOptions>;
    groupingToMatrixTransformer: import("..").DataTransformerInfo<import("./transformers/groupingToMatrix").GroupingToMatrixTransformerOptions>;
    limitTransformer: import("..").DataTransformerInfo<import("./transformers/limit").LimitTransformerOptions>;
    groupToNestedTable: import("..").DataTransformerInfo<import("./transformers/groupToNestedTable").GroupToNestedTableTransformerOptions>;
};
